area/docs: ["/docs"]
area/ui: ["/ui", "/provider-ui"]
component/mesheryctl: ["/mesheryctl"]
component/api: ["/handlers"]
language/go: ["*.go"]
language/markdown: ["*.md"]
language/javascript: ["*.js"]
backend: ["/app", "*.rb"]
legal: ["LICENSE*", "NOTICES*"]
area/ci: .github