area/docs:
- 'docs/**/*'
area/ci:
- '.github/**/*'      
component/ui:
- 'ui/**/*'
- 'provider-ui/**/*'
component/mesheryctl:
- 'mesheryctl/**/*'
component/extension:
- 'install/docker-extension/**/*'
area/lifecycle:
- 'install/deployment_yamls/*'
framework/helm:
- 'install/kubernetes/helm/**/*'
