area/docs:
  files: 
    - "docs/pages/*"
    - "docs/_includes/*"
    - "docs/_layouts/*"

component/api:
  files: 
    - "handlers/**/*"

component/mesheryctl:
  files: 
    - "mesheryctl/**/*"

language/go:
  files: 
    - "./*.go"

language/javascript:
  files: 
    - "./*.js"

language/markdown:
  files: 
    - "./*.md"

language/ruby:
  files: 
    - "./*.rb"

language/html:
  files: 
    - "./*.html"

area/ui:
  files: 
    - "ui/**/*"
    - "provider-ui/**/*"

area/tests:
  files: 
    - "ui/cypress/**/*"
    - "provider-ui/cypress/**/*"

area/ci:
  files: 
    - ".github/**/*"
