apiVersion: v1
kind: Pod
metadata:
  name: test-1
  namespace: test
  labels:
    name: a
spec:
  containers:
    - name: a
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
