{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meshery-traefix-mesh.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "meshery-traefix-mesh.labels" . | nindent 4 }}
{{- end -}}
