name: Docker Extension for Meshery
on:
  push:
    tags:
      - 'v*'  
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      # - '.github/**'
  workflow_dispatch:
    inputs:
      release-ver:
          description: 'Stable Release Version'     
          required: true
          default: 'v0.6.0-rc-'
      stripped-release-ver:
          description: 'Stripped Stable Release Version'     
          required: true
          default: '0.6.0-rc-'
      release-channel:
          description: 'Release Channel'     
          required: true
          default: 'edge'

env:
  GIT_VERSION: ${{github.events.input.release-ver}}
  GIT_STRIPPED_VERSION: ${{github.events.input.stripped-release-ver}}
  RELEASE_CHANNEL: ${{github.events.input.release-channel}}

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo "GIT_VERSION: ${{github.events.input.release-ver}}"
      echo "GIT_STRIPPED_VERSION: ${{github.events.input.stripped-release-ver}}"
      echo "RELEASE_CHANNEL: ${{github.events.input.release-channel}}"
 