name: Notify Meshery Extensions channel build
on:
  workflow_dispatch:

jobs:
  notfiy-build:
    name: Notify providers for Meshery Extensions channel build
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-latest 
    uses: layer5labs/meshery-extensions-packages/.github/workflows/build-and-deploy-meshery-extensions-playground.yml@master
    secrets: inherit
