name: Meshery Build and Releaser (meshery-extensions channel)
on:
  workflow_dispatch:

jobs:
  docker-build-push:
    name: Docker build and push
    if: github.repository == 'meshery/meshery' && github.event_name != 'pull_request' && success()
    env:
      RELEASE_CHANNEL: "kanvas"
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.branch }}
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build & tag
        run: |
          DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile --no-cache -t ${{ secrets.IMAGE_NAME }}:kanvas-latest --build-arg TOKEN=${{ secrets.GLOBAL_TOKEN }} --build-arg GIT_COMMITSHA=${GITHUB_SHA::8} --build-arg GIT_VERSION=${{ env.LATEST_TAG }} --build-arg RELEASE_CHANNEL=${RELEASE_CHANNEL} .
          
          docker tag ${{ secrets.IMAGE_NAME }}:kanvas-latest ${{ secrets.IMAGE_NAME }}:kanvas-${GITHUB_SHA::8}
          
          docker tag ${{ secrets.IMAGE_NAME }}:kanvas-latest ${{ secrets.IMAGE_NAME }}:kanvas-${GITHUB_REF/refs\/tags\//}
      - name: Docker push
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:kanvas-latest
          docker push ${{ secrets.IMAGE_NAME }}:kanvas-${GITHUB_SHA::8}
          docker push ${{ secrets.IMAGE_NAME }}:kanvas-${GITHUB_REF/refs\/tags\//}
  call-meshery-extensions-playground-rollout:
    needs:
      - docker-build-push
    name: Deploy CNCF Extensions Playground
    uses: layer5labs/meshery-extensions-packages/.github/workflows/deploy-meshery-extensions-playground.yml@master
    with:
      image: layer5/meshery:kanvas-${GITHUB_REF/refs\/tags\//}
    secrets: inherit
  