name: Docker Desktop Extension for Meshery
  # TODO 
  ##   1) Incorporate mesheryctl binaries into each DDE image

on:
  push:
    tags:
      - 'v*'  
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Release Channel
        id: release-channel
        run: |
          if [[ ${{ github.ref }} = refs/tags* ]]
          then
              echo "RELEASE_CHANNEL=stable" >> $GITHUB_ENV
          else
              echo "RELEASE_CHANNEL=edge" >> $GITHUB_ENV
          fi
          echo "Release channel determined to be $RELEASE_CHANNEL"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: meshery/meshery-docker-desktop-extension
          flavor: |
            latest=false
            prefix=${{env.RELEASE_CHANNEL}}-
          tags: |
            type=raw,value={{sha}}
            type=raw,value={{tag}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=latest
            type=semver,pattern={{version}}

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Move cache
        run:
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - 
        name: Build and Push 
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:install/docker-desktop-extension"
          push: true
          tags: ${{ steps.meta.outputs.tags }}     

      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: meshery/meshery-docker-desktop-extension   