name: email test
on:
    workflow_dispatch:
    
jobs:
  email-meshery-release-notes-workflow:
    name: Email Meshery Release Notes
    uses: layer5labs/meshery-extensions-packages/.github/workflows/notify-email.yml@master
    secrets: inherit
