name: eslint-check
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - working-directory: ./ui/
    - name: Run ESLint
      run: npx eslint .