name: Release Charts
on:
  push:
    branches:
      - 'master'
    paths:
      - 'install/kubernetes/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'install/kubernetes/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          charts_dir: install/kubernetes/helm/
          owner: layer5io
          repository: meshery.io
          branch: master
          target_dir: charts
          commit_username: l5io
          commit_email: l5io@layer5.io