name: MeshModel Component Generator and Updater
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run-script:
    name: Run Script
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 1
          
      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: "1.21"
      - name: Run component generation
        run: |
            cd scripts/component_generation; GOPROXY=https://proxy.golang.org,direct GOSUMDB=off go run main.go 1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw
      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "New Meshmodel components generated"
          branch: master
      
      - name: Send Email on Meshmodel Generators Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Actions - Workflow Failure
          from: |
            "Meshmodel Generator" <no-reply@meshery.io>
          to: developers@meshery.io
          body: |
            The GitHub Actions workflow in ${{ github.repository }} has failed.
            You can find more details in the GitHub Actions log ${{ github.workflow }}.