name: Release Drafter

on:
  push:
    # our release branch
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Drafting release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
      
      - name: Write release notes to markdown file
      - uses: actions/checkout    
        run: |
          CONTENT=${{ steps.release_drafter.outputs.body }}
          TAG=${{ steps.release_drafter.outputs.tag_name }}
          printf '%b\n' "---\nlayout: default\n---\n\n${CONTENT}" > ./docs/_releases/${TAG}.md
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.RELEASE_NOTES_PAT }}
          commit-message: "Created release note file ${{ steps.release_drafter.outputs.tag_name }}.md"
          committer: l5io <ci@layer5.io>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: docs/automated-release-notes
          delete-branch: true
          title: '[Docs] Release Notes for Meshery ${{ steps.release_drafter.outputs.tag_name }}'
          body: |
            An auto-generated pull request to document release notes for Meshery ${{ steps.release_drafter.outputs.tag_name }}
          labels: |
            area/docs
            area/ci
          # assignees:
          # reviewers:
          team-reviewers: |
            release-team
            maintainers
          # milestone: 1
          draft: false

      - name: Verify PR
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"